<?php

namespace AppBundle\Repository;

/**
 * Data_ReferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Data_ReferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
